name: Release Web-Frontend
on:
  # Trigger when a new release is published
  release:
    types: [published]
    
jobs:
  # This workflow contains a single job called "build"
  set_version_number:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set release_env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Replace Version in package.json
        uses: jaywcjlove/github-action-package@main
        with:
          version: ${{ env.RELEASE_VERSION }}
